### ISSUE TITLE
RunTimeError

### ISSUE THREAD

**Issue by ghost** [yatengLG/Retinanet-Pytorch#22]
Traceback (most recent call last):
  File "F:/Retinanet-Pytorch-master/Demo_train.py", line 36, in <module>
    trainer(net, train_dataset)
  File "F:\Retinanet-Pytorch-master\Model\trainer.py", line 115, in __call__
    reg_loss, cls_loss = self.loss_func(cls_logits, bbox_preds, labels, boxes)
  File "D:\anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "F:\Retinanet-Pytorch-master\Model\struct\MultiBoxLoss.py", line 57, in forward
    predicted_locations = predicted_locations[pos_mask, :].view(-1, 4)
RuntimeError: copy_if failed to synchronize: device-side assert triggered
配置文件里面将batch_size减小为1，学习率也进行了修改为1e-4，还是报错，请问是什么原因

**Comment by ghost** [comment]
在iter为70的时候停止了

**Comment by yatengLG** [comment]
能跑就不是代码的问题，你可以检查下是否你数据里面有空数据。

**Comment by yatengLG** [comment]
这个是在做掩码的时候，出错的，
 predicted_locations = predicted_locations[pos_mask, :].view(-1, 4)
也就是这个索引是不存在的，pos_mask全为空，也就是运行到一个数据里面没有正例。
所以掩码出问题了，然后空数据view失败了

**Comment by ghost** [comment]
> 这个是在做掩码的时候，出错的，
> predicted_locations = predicted_locations[pos_mask, :].view(-1, 4)
> 也就是这个索引是不存在的，pos_mask全为空，也就是运行到一个数据里面没有正例。
> 所以掩码出问题了，然后空数据view失败了

嗷嗷，好的，我需要做的就是去检查数据吗？

**Comment by yatengLG** [comment]
对的，你排查下数据里面，有没有空数据，就是不存在你需要检测的目标的，删了就好了。

**Comment by ghost** [comment]
> 对的，你排查下数据里面，有没有空数据，就是不存在你需要检测的目标的，删了就好了。
我现在将数据集改变为voc07的数据集，但是同样的出现了此错误

**Comment by fengzhiguroll** [comment]
我也是这样的情况，换成VOC数据集，出现同样的错误
报错：RuntimeError: copy_if failed to synchronize: cudaErrorAssert: device-side assert triggered
